language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - nightly

env:
    - TEST_PHP_ARGS="-q"

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install -y liblzma-dev

before_script:
    - phpize
    - ./configure
    - make
    - sudo make install
    - echo "extension=xz.so" >> `php --ini | grep "Loaded Configuration File:" | sed -e "s/.*:\s*//"`

script:
    - make test

matrix:
    allow_failures:
        - php: nightly
